//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AIPI.rc
//
#define IDR_AIPITYPE_CNTR_IP            6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_QUERY                       101
#define IDP_FAILED_TO_CREATE            102
#define IDD_GRAPH_AXISPROPPAGE_DLG      103
#define IDR_POPUP_MENU                  103
#define IDB_BANNER256                   103
#define IDD_GRAPH_GRAPHICS_PROPS        104
#define IDB_BANNER16                    104
#define IDB_WATERMARK16                 105
#define IDB_WATERMARK256                106
#define IDB_FONT                        127
#define IDR_MAINFRAME                   128
#define IDR_AIPITYPE                    129
#define IDC_DROP_COPY_ROOT              130
#define IDD_JUKEBOX_DLG                 131
#define IDB_IMAGEMULTILISTCTRL          131
#define IDC_DROP_MOVE_ABOVE             131
#define IDB_SPLASHWINDOW                132
#define IDC_DROP_COPY_ABOVE             132
#define IDB_IL_LISTBOXCHK               133
#define IDI_ADMIRATION                  134
#define IDR_APITYPE                     134
#define IDI_ERROR_SEMANT                134
#define IDR_TREEEDTYPE                  135
#define IDD_CHART_LINEPROP_DLG          135
#define IDR_PROJTYPE                    136
#define IDD_CHART_SURFACEPROP_DLG       137
#define IDD_COMMAND_DLG                 138
#define IDB_TREE                        138
#define IDD_CHART_POINTPROP_DLG         139
#define IDC_NODROP                      140
#define IDI_ERROR_LEX                   140
#define IDI_ERROR_QUESTION              141
#define IDC_DROP_MOVE_ROOT              142
#define IDI_ERROR_SYNTAX                142
#define IDI_ERROR_STOP                  143
#define IDC_DROP_COPY_SON               144
#define IDC_DROP_MOVE_SON               146
#define IDD_DXFCAD_DLG                  147
#define IDB_BACKGROUND                  148
#define IDB_TABLISTIMAGES               149
#define IDD_TREE_PROP_DLG               150
#define IDR_TOOLBAR_CUSTOMIZE           150
#define IDD_INDUCTION_FRAME_DLG         151
#define IDD_PAGEFILE_DLG                152
#define IDB_LISTCHECKBOXES              153
#define IDD_PAGEEDIT_DLG                153
#define IDD_PAGECELLSIZE_DLG            155
#define IDD_PAGEFORMAT_DLG              156
#define IDI_JUKEBOX_PAUSE               157
#define IDD_PAGEOPTIONS_DLG             157
#define IDI_JUKEBOX_PLAY                158
#define IDI_GRID                        159
#define IDB_TABINDUCTIONIMAGES          162
#define IDC_WAIT01                      163
#define IDR_PROPERTYBAR                 164
#define IDI_JUKEBOX_FRAMESTEP           170
#define IDI_JUKEBOX_STOP                172
#define IDI_JUKEBOX_GRAPHEDIT           175
#define IDD_IMAGE_DLG                   176
#define IDD_MEDIAPLAYER_DLG             178
#define IDD_IMAGEFILTER_DLG             179
#define IDD_STRINGINPUT_DLG             180
#define IDI_AIPI16                      180
#define IDI_AIPI32                      181
#define IDI_AIPI48                      182
#define IDI_AIPI_LOGO                   183
#define IDI_AIPI_MONO                   184
#define IDI_AIPI_TEST                   185
#define IDR_IMAGECTRL                   187
#define IDI_AIPI_COLOR                  188
#define IDR_IMAGEDLG                    189
#define IDI_ICON1                       189
#define IDI_AiPI1616                    190
#define IDI_AiPI4848                    191
#define IDD_FINDINFILES_DLG             192
#define IDI_AiPI2424                    192
#define IDI_CHECKMARK                   193
#define IDI_ERROR_INFO                  193
#define IDI_AiPI3232                    195
#define IDI_AiPI4848_MONO               196
#define IDI_AiPILOGO16                  213
#define IDI_AiPILOGO32                  215
#define IDI_AIPI_BLUE_16                216
#define IDD_AIPI_FRAME_DLG              219
#define IDB_TABTREEIMAGES               236
#define IDB_RULESIMAGES                 237
#define IDB_LETTERSIMAGES               237
#define IDB_FILESBMP                    238
#define IDB_RESOURCEIMAGES              239
#define IDD_PAGEINSERT_DLG              246
#define IDI_ERROR_WARNING               252
#define IDI_FIND1                       255
#define IDI_FIND2                       256
#define IDI_FIND3                       257
#define IDI_ICON2                       258
#define IDI_FINDINFILES                 258
#define IDI_ICON3                       259
#define IDI_FINDEXT                     259
#define IDI_ICON4                       260
#define IDI_CLSFOLDER                   260
#define IDI_ICON6                       263
#define IDI_KNW                         263
#define IDI_ICON8                       265
#define IDI_BOOK                        265
#define IDI_AIPI_GRAY                   266
#define IDI_TREE_TYPE                   267
#define IDI_IDT                         267
#define IDI_FINDINFILES_STOP            268
#define IDD_OLEDB_CONNECTION_DLG        274
#define IDI_TREE                        276
#define IDI_CSV                         277
#define IDI_RTF                         278
#define IDI_JUKEBOX_PROPERTIES          279
#define IDR_SCINTITYPE_TXT              280
#define IDI_AIPI_BLUE_17                281
#define IDI_XLS                         282
#define IDI_APJ                         292
#define IDI_XLS_NET                     296
#define IDR_METERCTRL                   298
#define IDI_TXT                         299
#define IDI_TXT_EXT                     300
#define IDI_XLS_FILE                    301
#define IDI_WORDPAD                     302
#define IDI_NOTEPAD                     304
#define IDI_SSN                         306
#define IDD_NSCHART_DLG                 307
#define IDI_KNW_EXT                     308
#define IDI_KNW_FILE                    310
#define IDB_DATABASEIMAGES              311
#define IDB_WORKSPACEIMAGES             312
#define IDR_NSCHART                     313
#define IDI_ICON5                       316
#define IDI_SAVE_ALL                    316
#define IDB_AIPI_LOGO                   317
#define IDD_CHART_SERIESDEL_DLG         318
#define IDB_EMPTY_SCREEN                318
#define IDI_SAVE_AS                     319
#define IDD_CHART_AXISOPTIONS_DLG       320
#define IDD_CHART_SERIESPROP_DLG        321
#define IDD_GRAPH_CHANGETITLE_DLG       322
#define IDI_FILE_PROJECT                322
#define IDI_OPEN_PROJECT                324
#define IDI_NEW_PROJECT                 326
#define IDR_CHARTBAR                    327
#define IDI_FILE_PROJ                   328
#define IDI_OPEN_PROJ                   330
#define IDI_NEW_PROJ                    331
#define IDB_PROJ_NEW                    332
#define IDD_CALENDAR_DLG                333
#define IDB_PROJ_OPEN                   333
#define IDD_CALENDARINPUT_DLG           334
#define IDD_CALENDARDATE_DLG            335
#define IDD_GRAPH_GRAPHPROPPAGE_DLG     336
#define IDD_GRAPH_COORDINATES_DLG       337
#define IDD_GRAPH_AXIS_DLG              338
#define IDD_OLEDB_DLG                   339
#define IDR_CALENDARCTRL                340
#define IDD_DXFPROGRESS_DLG             340
#define IDD_OPEN_DELIMITER_DLG          341
#define IDD_FINDINFILES_EXT_DLG         342
#define IDD_NEWPROJECT_INTROPAGE        343
#define IDD_NEWPROJECT_PAGE1            344
#define IDD_NEWPROJECT_PAGE2            345
#define IDD_NEWPROJECT_ENDPAGE          346
#define IDB_WINDOWS2000_HARDWARE        347
#define IDB_WINDOWS2000_PRINT           348
#define IDB_WINDOWS2000_ARROWS          349
#define IDR_GRAPHBAR                    350
#define IDD_SCINTILLA_ZOOM              350
#define IDD_ZOOMVIEW_DLG                351
#define IDB_FILEIMAGES                  354
#define IDI_SSN_FILE                    355
#define IDI_CLOSE_PROJECT               356
#define IDI_RULE_CLOSE_BOOK             358
#define IDI_RULE_OPEN_BOOK              359
#define IDI_RULE_LIGHT_ON               360
#define IDI_RULE_LIGHT_OFF              361
#define IDI_RULE_BOX_OPEN               362
#define IDI_RULE_BOX_CLOSE              363
#define IDI_RULE_SUN_HOT                364
#define IDI_RULE_SUN_COLD               365
#define IDB_RULEIMAGES                  366
#define IDI_DXF_FILE                    367
#define IDI_CAD_FILE                    368
#define IDD_GOTO_DLG                    369
#define IDI_JS                          373
#define IDI_VBS                         374
#define IDI_AIPI_JUANCARLOS             376
#define IDR_LISTOPTION                  377
#define IDR_MULTILISTDLG                392
#define IDB_TABLISTIMAGES1              393
#define IDB_IMAGELIST                   393
#define IDR_SCINTITYPE1                 394
#define IDR_TREEEDTYPE1                 395
#define IDB_LIST_CHECKBOXES             396
#define IDR_IPI                         396
#define IDB_TABAIPIIMAGES               397
#define IDR_TREEEDTYPE2                 398
#define IDC_ROLLUPCTRL                  400
#define IDC_RICHEDITCTRL1               401
#define IDC_RICHEDITCTRL2               402
#define IDC_STATIC_EX                   791
#define IDC_EDIT_EX                     792
#define IDC_GRAPHBARCTRL                793
#define IDC_LISTCTRL_EX                 794
#define IDC_3DMETERCTRL                 795
#define IDC_CALENDARCTRL                796
#define IDC_CHARTBARCTRL                797
#define IDC_NSCHARTBARCTRL              798
#define IDC_LISTBOX_EX                  799
#define IDC_ST_IMG                      800
#define IDC_LISTCTRL1                   801
#define IDC_LISTCTRL2                   802
#define IDC_LISTCTRL3                   803
#define IDC_LISTCTRL4                   804
#define IDC_LISTCTRL5                   805
#define IDC_COMBO_COMMAND               1000
#define IDC_DATETIMEPICKER1             1000
#define IDC_OLEDB_EDITQUERY             1000
#define IDC_EDIT_DSN_D                  1000
#define IDC_DELIMITER                   1000
#define IDC_STATIC_COMMAND              1001
#define IDC_EDIT_UID_D                  1001
#define IDC_STATIC_GROUP                1001
#define IDC_MOVIE_SCREEN                1002
#define IDC_OLEDB_STATICQUERY           1002
#define IDC_EDIT_PWD_D                  1002
#define IDC_SLIDER                      1003
#define IDC_OLEDB_LISTCTRL              1003
#define IDC_EDIT_DATABASE_NAME          1003
#define IDC_PROGDLG_PROGRESS            1003
#define IDC_STATIC_POSITION             1004
#define IDC_EDIT_CALENDARTEXT           1004
#define IDC_PROGDLG_PERCENT             1004
#define IDC_STATUS                      1005
#define IDC_CHECK_MUTE                  1006
#define IDC_GRAPH_TITLE                 1006
#define IDC_CHECK_LOOP                  1007
#define IDC_STATIC_IMAGESIZE            1008
#define IDC_GRAPH_CH_TITLE              1008
#define IDC_CHECK_WHOLEWORD             1008
#define IDC_BUTTON_PLAY                 1009
#define IDC_CHECK_MATCHCASE             1009
#define IDC_BUTTON_STOP                 1010
#define IDC_GRAPH_CH_COLOR              1010
#define IDC_CHECK_REGEXP                1010
#define IDC_BUTTON_PAUSE                1011
#define IDC_STATICPROMPT                1011
#define IDC_SERIESTYPE_COMBO            1011
#define IDC_BUTTON_HELP                 1011
#define IDC_BUTTON_FRAMESTEP            1012
#define IDC_SERIESCOLOUR_BTN            1012
#define IDC_X1                          1012
#define ID_STATIC_FIND                  1012
#define IDC_BUTTON_GRAPHEDIT            1013
#define IDC_X2                          1013
#define IDC_STATIC_VOLUME               1014
#define IDC_SLIDER_VOLUME               1015
#define IDC_STATIC_FILTERS              1016
#define IDC_Y1                          1016
#define IDC_LIST_FILTERS                1017
#define IDC_Y2                          1017
#define IDC_STATIC_DURATION             1018
#define IDC_GEN_GRAPH_PROPS_AXIS        1018
#define IDC_XTITLE                      1018
#define IDC_BUTTON_SET_MEDIADIR         1019
#define IDC_EDIT_MEDIADIR               1020
#define IDC_XUOM                        1020
#define IDC_CHECK_FULLSCREEN            1021
#define IDC_GRAPH_CHOICE                1021
#define IDC_YTITLE                      1021
#define IDC_STATIC_FILEDATE             1022
#define IDC_YUOM                        1022
#define IDC_STATIC_FILESIZE             1023
#define IDC_GRAPH_HIDESHOW              1023
#define IDC_BUTTON_PROPPAGE             1024
#define IDC_GRAPH_POINTMARKS            1024
#define IDC_STATIC_DATASOURCE_CAPTION   1024
#define IDC_STATIC_DATASOURCE           1024
#define IDC_GRAPH_MOUSECOORDS           1026
#define IDC_OLEDB_TREECTRL              1026
#define IDC_MP_MOVIE_SCREEN             1027
#define IDC_STC_BRIGHTNESS              1027
#define IDC_XAXIS_PRECISION             1027
#define IDC_OLEDB_BUTTONQUERY           1027
#define IDC_MP_SLIDER                   1028
#define IDC_GRAPHS_SHOWALL              1028
#define IDC_YAXIS_PRECISION             1028
#define IDC_MP_CHECK_MUTE               1029
#define IDC_MP_CHECK_LOOP               1030
#define IDC_MP_BUTTON_PLAY              1031
#define IDC_MP_BUTTON_STOP              1032
#define IDC_MP_BUTTON_BROWSE            1033
#define IDC_MP_BUTTON_PAUSE             1034
#define IDC_VERTICALAXIS_COMBO          1034
#define IDC_STATIC_PATH                 1034
#define IDC_STATIC_DATABASE             1034
#define IDC_MP_STATIC_VOLUME            1035
#define IDC_STATIC_LABEL                1035
#define IDC_HORIZONTALAXIS_COMBO        1035
#define IDC_STATIC_USER                 1035
#define IDC_MP_SLIDER_VOLUME            1036
#define IDC_LABEL                       1036
#define IDC_LINEDATA_RADIO              1036
#define IDC_STATIC_PASSWORD             1036
#define IDC_MP_CHECK_FULLSCREEN         1037
#define IDC_STATIC_VALUE                1037
#define IDC_SINEDATA_RADIO              1037
#define IDC_BTN_OLEDB_BROWSE            1037
#define IDC_MP_EDIT_MEDIADIR            1038
#define IDC_VALUE                       1038
#define IDC_RANDOMDATA_RADIO            1038
#define IDC_OLEDB_SPINTABLE             1038
#define IDC_MINXVALUE_EDIT              1039
#define IDC_OLEDB_CHECKTABLE            1039
#define IDC_MAXXVALUE_EDIT              1040
#define IDC_PROGRESS_CAPTION            1040
#define IDC_STATIC_NSCHART              1043
#define IDC_POINTSNUMBER_EDIT           1043
#define IDC_STATIC_DXFWND               1043
#define IDC_LIST_SERIES                 1044
#define IDC_DATAPARAM1_EDIT             1044
#define IDC_BUTTON_FONT_PICKER          1044
#define IDC_STATIC_SERIES               1045
#define IDC_DATAPARAM2_EDIT             1045
#define IDC_COMBO_FONT_PICKER           1045
#define IDC_DATAPARAM1_TEXT             1046
#define IDC_STATIC_FONT_PICKER          1046
#define IDC_LEFTAXIS_RADIO              1047
#define IDC_DATAPARAM2_TEXT             1047
#define IDC_RIGHTAXIS_RADIO             1048
#define IDC_INDUCTIONTAB                1048
#define IDC_TOPAXIS_RADIO               1049
#define IDC_LIST1                       1049
#define IDC_INDUCTION_LIST1             1049
#define IDC_AXISVISIBLE_CHECK           1050
#define IDC_LIST2                       1050
#define IDC_INDUCTION_LIST2             1050
#define IDC_AXISLOGARITHMIC_CHECK       1051
#define IDC_STATIC_ATRIBUTES            1051
#define IDC_AXISINVERTED_CHECK          1052
#define IDC_STATIC_SEL_ATRIBUTES        1052
#define IDC_AXISAUTOMATIC_CHECK         1053
#define IDC_GRID                        1053
#define IDC_AXISGRIDVIS_CHECK           1054
#define IDC_BTN_OPENFILE                1054
#define IDC_AXISMINVAL_EDIT             1055
#define IDC_BTN_CONNECTDB               1055
#define IDC_AXISMAXVAL_EDIT             1056
#define IDC_BTN_PRINT                   1056
#define IDC_AXISLABEL_EDIT              1057
#define IDC_BTN_CUT                     1057
#define IDC_BOTTOMAXIS_RADIO            1058
#define IDC_PENSTYLE_COMBO              1058
#define IDC_BTN_COPY                    1058
#define IDC_AXISMINVAL_STATIC           1059
#define IDC_LINEWIDTH_EDIT              1059
#define IDC_BTN_PASTE                   1059
#define IDC_AXISMAXVAL_STATIC           1060
#define IDC_HORIZONTAL_RADIO            1060
#define IDC_BTN_SELECTALL               1060
#define IDC_AXISLABEL_STATIC            1061
#define IDC_RADIO_READ                  1061
#define IDC_FILLSTYLE_COMBO             1062
#define IDC_STATIC_X_AXIS               1062
#define IDC_RADIO_WRITE                 1062
#define IDC_POINTTYPE_COMBO             1063
#define IDC_STATIC_Y_AXIS               1063
#define IDC_STATIC_SEPARATOR            1063
#define IDC_POINTWIDTH_EDIT             1064
#define IDC_STATIC_X_AXIS_TITLE         1064
#define IDC_STATIC_MODE                 1064
#define IDC_STATIC_SEPARATOR04          1064
#define IDC_POINTHEIGHT_EDIT            1065
#define IDC_STATIC_X_AXIS_UOM           1065
#define IDC_STATIC_X_AXIS_PRECISION     1066
#define IDC_STATIC_Y_AXIS_TITLE         1067
#define IDC_STATIC_Y_AXIS_UOM           1068
#define IDC_STATIC_Y_AXIS_PRECISION     1069
#define IDC_SPIN_ROWS                   1069
#define IDC_STATIC_GENERAL_COORDINATES  1070
#define IDC_EDIT_ROWS                   1070
#define IDC_STATIC_GENERAL_X1           1071
#define IDC_STATIC_ROWS                 1071
#define IDC_STATIC_GENERAL_X2           1072
#define IDC_STATIC_GENERAL_Y1           1073
#define IDC_SPIN_COLUMNS                1073
#define IDC_STATIC_GENERAL_Y2           1074
#define IDC_EDIT_COLUMNS                1074
#define IDC_STATIC_COLUMNS              1075
#define IDC_SPIN_FIXEDROWS              1076
#define IDC_EDIT_FIXEDROWS              1077
#define IDC_STATIC_FIXEDROWS            1078
#define IDC_STATIC_PENSTYLE             1079
#define IDC_SPIN_FIXEDCOLUMNS           1079
#define IDC_STATIC_LINEWIDTH            1080
#define IDC_EDIT_FIXEDCOLUMNS           1080
#define IDC_STATIC_FILLSTYLE            1081
#define IDC_STATIC_FIXEDCOLUMNS         1081
#define IDC_VERTICAL_RADIO              1082
#define IDC_STATIC_NO_CELLS             1082
#define IDC_STATIC_SERIESPROP           1083
#define IDC_BTN_AUTOFILLGRID            1083
#define IDC_STATIC_SERIESTYPE           1084
#define IDC_BTN_AUTOSIZE                1084
#define IDC_STATIC_SERIESCOLOR          1085
#define IDC_BTN_EXPANDCOLUMN            1085
#define IDC_STATIC_SERIESNAME           1086
#define IDC_BTN_FITCELL                 1086
#define IDC_STATIC_VERTICALAXIS         1087
#define IDC_STATIC_HORIZONTALAXIS       1088
#define IDC_BTN_INSERTROW               1088
#define IDC_STATIC_SERIESDATA           1089
#define IDC_BTN_INSERTCOLUMN            1089
#define IDC_BTN_DELETEROW               1089
#define IDC_STATIC_MINX_VAL             1090
#define IDC_CHK_ROWRESIZE               1090
#define IDC_STATIC_MAXX_VAL             1091
#define IDC_CHK_COLUMNRESIZE            1091
#define IDC_STATIC_POINTS               1092
#define IDC_STATIC_GRIDLINES            1092
#define IDC_STATIC_POINTSTYPE           1093
#define IDC_CHK_HORIZONTAL              1093
#define IDC_STATIC_POINTSWIDTH          1094
#define IDC_CHK_VERTICAL                1094
#define IDC_STATIC_POINTSHEIGHT         1095
#define IDC_STATIC_FONT                 1095
#define IDC_STATIC_PICKDATE             1096
#define IDC_BTN_FONT                    1096
#define IDC_XTITLE_DLG                  1097
#define IDC_XUOM_DLG                    1098
#define IDC_XAXIS_PRECISION_DLG         1099
#define IDC_RADIO_FIXEDITALIC           1099
#define IDC_YTITLE_DLG                  1100
#define IDC_RADIO_FIXEDBOLD             1100
#define IDC_YUOM_DLG                    1101
#define IDC_RADIO_FIXEDVERTICAL         1101
#define IDC_YAXIS_PRECISION_DLG         1102
#define IDC_CHK_TOOLTIPS                1102
#define IDC_STATIC_X_AXIS_DLG           1103
#define IDC_CHK_SORT                    1103
#define IDC_STATIC_X_AXIS_TITLE_DLG     1104
#define IDC_STATIC_FOCUS                1104
#define IDC_STATIC_X_AXIS_UOM_DLG       1105
#define IDC_STATIC_SORT                 1105
#define IDC_STATIC_X_AXIS_PRECISION_DLG 1106
#define IDC_CHECK_CELLSELECT            1106
#define IDC_STATIC_Y_AXIS_DLG           1107
#define IDC_STATIC_Y_AXIS_TITLE_DLG     1108
#define IDC_CHK_LISTMODE                1108
#define IDC_STATIC_Y_AXIS_UOM_DLG       1109
#define IDC_CHK_SINGLEROW               1109
#define IDC_STATIC_Y_AXIS_PRECISION_DLG 1110
#define IDC_CHK_VIRTUALMODE             1110
#define IDC_CHK_CALLBACKFUNCTION        1111
#define IDC_CHK_FITGRID                 1114
#define IDC_STATIC_GENERAL_COORDINATES_DLG 1115
#define IDC_STATIC_NCELLS               1115
#define IDC_STATIC_GENERAL_X1_DLG       1116
#define IDC_STC_ROWS                    1116
#define IDC_STATIC_GENERAL_X2_DLG       1117
#define IDC_EDIT_NROWS                  1117
#define IDC_X1_DLG                      1118
#define IDC_SPIN_NROWS                  1118
#define IDC_X2_DLG                      1119
#define IDC_STC_COLS                    1119
#define IDC_STATIC_GENERAL_Y1_DLG       1120
#define IDC_EDIT_NCOLS                  1120
#define IDC_STATIC_GENERAL_Y2_DLG       1121
#define IDC_SPIN_NCOLS                  1121
#define IDC_Y1_DLG                      1122
#define IDC_EDIT_NFIXROWS               1122
#define IDC_Y2_DLG                      1123
#define IDC_SPIN_NFIXROWS               1123
#define IDC_STC_FIXCOLS                 1124
#define IDC_EDIT_NFIXCOLS               1125
#define IDC_SPIN_NFIXCOLS               1126
#define IDC_BTN_SAVEAS                  1127
#define IDC_STATIC_SEPARATOR01          1128
#define IDC_RADIO_FIXEDNORMAL           1129
#define IDC_STATIC_QUERY                1130
#define IDC_INDUCTION_TREECTRL          1132
#define IDC_STATIC_GRAPH                1136
#define IDC_INDUCTION_CHECKGRAPH        1137
#define IDC_INDUCTION_GRAPH             1138
#define IDC_INDUCTION_CHECKVALUES       1139
#define IDC_STATIC_TABLES               1140
#define IDC_STATIC_DATA                 1141
#define IDC_INDUCTION_SPIN              1143
#define IDC_SCINCTRL                    1145
#define IDC_CHECK_VIEWQUERY             1146
#define IDC_CHECK_VIEWTABLES            1147
#define IDC_CHECK_VIEWDATA              1148
#define IDC_CHECK_TABLEV                1149
#define IDC_RADIO_DB2                   1150
#define IDC_RADIO_MSACCESS              1151
#define IDC_RADIO_MSSQL                 1152
#define IDC_RADIO_MSORACLE              1153
#define IDC_RADIO_MYSQL                 1154
#define IDC_RADIO_ORACLE                1155
#define IDC_BTN_EXECQUERY               1156
#define IDC_STATIC_SEPARATOR02          1157
#define IDC_STATIC_SEPARATOR03          1158
#define IDC_AIPI_GRID                   1159
#define IDC_GRID_LHS                    1159
#define IDC_STC_LABEL_RANGE             1161
#define IDC_EDIT_MIN_RANGE              1162
#define IDC_STATIC_TO                   1163
#define IDC_EDIT_MAX_RANGE              1165
#define IDC_BTN_RANGE                   1167
#define IDC_AIPITAB                     1168
#define IDC_STC_RANGE                   1169
#define IDC_STC_AIPI_DATA               1170
#define IDC_GRID_WM                     1171
#define IDC_GRID_AM                     1172
#define IDC_GRID_BM                     1173
#define IDC_GRID_AGENDA                 1174
#define IDC_GRID_RETE                   1175
#define IDC_BTN_INSERTCOL               1177
#define IDC_BTN_DELETECOL               1178
#define IDC_STATIC_SEPARATOR05          1179
#define IDC_STATIC_NROWS                1180
#define IDC_STATIC_NCOLS                1181
#define IDC_BTN_ALL                     1182
#define IDC_GRID_BM_TK                  1183
#define IDC_STC_ROOT                    1184
#define IDC_EDITROOT                    1185
#define IDC_BTBROWSE                    1186
#define IDC_STC_MASK                    1187
#define IDC_EDITMASK                    1188
#define IDC_CKSUBFOLDERS                1189
#define IDC_CKSIZE                      1190
#define IDC_EDITMINSIZE                 1191
#define IDC_EDITMAXSIZE                 1192
#define ID_EDITTEXT                     1193
#define ID_STC_TEXT                     1194
#define IDC_EDIT_PROJ_NAME              1195
#define IDC_EDIT_PROJ_AUTHOR            1196
#define IDC_EDIT_PROJ_DESC              1197
#define IDC_EDIT_PROJ_ROOT              1198
#define IDC_STATIC_TITLE                1199
#define IDC_STATIC_INFO                 1200
#define IDC_STATIC_ADVICE               1201
#define IDC_STATIC_THAKS                1202
#define IDC_RADIO_FORDWARD              1203
#define IDC_RADIO_BACKWARD              1204
#define IDC_CHECK_IMAGES                1205
#define IDC_CHECK_VIDEOS                1206
#define IDC_CHECK_DB                    1207
#define IDC_CHECK_OTHER                 1208
#define IDC_IMAGE_NEW_PAGE2             1209
#define IDC_IMAGE_NEW_PAGE1             1210
#define IDC_RICHEDIT_PROJECT_INFO       1211
#define IDC_STATIC_ROOT                 1212
#define IDC_STATIC_EXPANSION            1221
#define IDC_RADIO_200                   1222
#define IDC_RADIO_100                   1223
#define IDC_RADIO_75                    1224
#define IDC_RADIO_50                    1225
#define IDC_RADIO_25                    1226
#define IDC_RADIO_CUSTOM                1227
#define IDC_EDIT_CUSTOM                 1228
#define IDC_SPIN_CUSTOM                 1229
#define IDC_RADIO_CHAR                  1230
#define IDC_RADIO_LINE                  1231
#define IDC_EDIT_GOTO                   1232
#define IDC_STATIC_GOTO                 1233
#define IDC_GRID_COND_LINK              1234
#define IDC_GRID_RHS                    1235
#define IDC_TREEVIEWCTRL1               1500
#define IDC_TREEVIEWCTRL2               1501
#define IDC_TREEVIEWCTRL3               1502
#define IDC_SLIDER_RED                  2000
#define IDC_SLIDER_GREEN                2001
#define IDC_TAB                         2001
#define IDC_SLIDER_BLUE                 2002
#define IDC_COMMA                       2002
#define IDC_OTHER                       2003
#define IDC_CHECK_INVERT                2005
#define IDC_SLIDER_CONTRAST             2006
#define IDC_BTN_BROWSE                  2007
#define IDC_PICWND                      2008
#define IDC_BTN_CANCEL                  2009
#define IDC_CHECK_BLACK_WHITE           2010
#define IDC_CHECK_BLUR                  2011
#define IDC_CHECK_SHARPNESS             2012
#define IDC_SCROLL_VERT_SIZE            2013
#define IDC_SCROLL_HORZ_SIZE            2014
#define IDC_STATIC_RED_LEVEL            2015
#define IDC_STATIC_GREEN_LEVEL          2016
#define IDC_STATIC_BLUE_LEVEL           2017
#define IDC_STATIC_CONTRAST_LEVEL       2018
#define IDC_STC_EFFECT                  2028
#define IDC_STATIC_RED                  2029
#define IDC_STATIC_GREEN                2030
#define IDC_STATIC_BLUE                 2031
#define IDC_STATIC_CONTRAST             2032
#define IDC_SERIESNAME_EDIT             3010
#define IDC_TITLE_STRING                3012
#define IDC_EDIT                        3018
#define ID_SETTINGS_SKIN_CLASSIC        4000
#define ID_SETTINGS_SKIN_OFFICEXP       4001
#define ID_SETTINGS_SKIN_OFFICE2003     4002
#define ID_CTRL_MULTIOPTION_UNSELECTALL 4037
#define ID_VIEW_ZOOM_IN                 22956
#define ID_VIEW_ZOOM_OUT                22957
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_OPTIONS_VIEW_LINENUMBERS     32771
#define ID_RENAME                       32771
#define ID_VIEW_VERTICALTREE            32771
#define ID_CALCULATE_LEVEL              32772
#define ID_VIEW_HORIZONTALTREE          32772
#define ID_VIEW_VERTICALTREE_PROPERTYDLG 32773
#define ID_VIEW_OUTPUTTABVIEW           32775
#define ID_ADD_CHILD                    32775
#define ID_VIEW_COMMANDDLGBAR           32776
#define ID_ADD_SIBLING                  32776
#define ID_SETTINGS_CUSTOMIZE           32777
#define ID_VIEW_WORKSPACE               32777
#define ID_VIEW_EDITWORKSPACETABVIEW    32777
#define ID_VIEW_CTRL_JUKEBOXDLG         32778
#define ID_VIEW_CTRL_MEDIAPLAYERDLG     32779
#define ID_OPTIONS_SELECTION_MARGIN     32779
#define ID_SORT_SUBTREE_ALPHABETIC      32779
#define ID_CUSTOMIZE_TEXT_COLOR         32779
#define ID_VIEW_CTRL_IMAGEDLG           32780
#define ID_OPTIONS_FOLD_MARGIN          32780
#define ID_SORT_SUBTREE_NUMERIC         32780
#define ID_CUSTOMIZE_BORDER_STYLE       32780
#define ID_VIEW_CTRL_IMAGECTRL          32781
#define ID_OPTIONS_ADDMARKER            32781
#define ID_CUSTOMIZE_FILL_COLOR         32781
#define ID_VIEW_CTRL_LISTOPTIONCTRL     32782
#define ID_OPTIONS_DELETEMARKER         32782
#define ID_CUSTOMIZE_BORDER_COLOR       32782
#define ID_VIEW_CTRL_NSCHARTBARCTRL     32783
#define ID_OPTIONS_FIND_NEXTMARKER      32783
#define ID_CUSTOMIZE_DASH_STYLE         32783
#define ID_VIEW_CTRL_CHARTBARCTRL       32784
#define ID_OPTIONS_FIND_PREVMARKER      32784
#define ID_CUSTOMIZE_LINE_STYLE         32784
#define ID_VIEW_CTRL_CALENDARDLG        32785
#define ID_VIEW_OUTPUT                  32785
#define ID_VIEW_EDITOUTPUTTABVIEW       32785
#define ID_VIEW_CTRL_STATICMETERCTRL    32786
#define ID_DEBUG_BUILD                  32786
#define ID_DELETE_ITEM                  32786
#define ID_VIEW_CTRL_IMAGEFILTERDLG     32787
#define ID_DELETE_ALL_ITEMS             32787
#define ID_CTRL_IMG_OPEN                32788
#define ID_CTRL_LISTBAR_INDENT          32789
#define ID_CTRL_LISTBAR_HIGHLIGHT       32790
#define ID_VIEW_CTRL_LISTMULTIOPTIONCTRL 32793
#define ID_OPTIONS_LANGUAGE             32793
#define ID_CTRL_LISTMULTIOPTION_FONTCOLOR 32795
#define ID_CTRL_LISTMULTIOPTION_FONTTYPE 32796
#define ID_CTRL_LISTMULTIOPTION_RESETFONTTYPE 32797
#define ID_CTRL_LISTMULTIOPTION_DELETEITEM 32798
#define ID_CTRL_LISTMULTIOPTION_CLEAR   32799
#define IDC_EXPAND_ALL_TREE             32799
#define ID_CTRL_LISTMULTIOPTION_SORT    32800
#define ID_CTRL_LISTMULTIOPTION_CHECKABLE 32801
#define ID_CTRL_LISTMULTIOPTION_MULTICHK 32802
#define ID_CTRL_IMG_RIGHT               32803
#define ID_CTRL_IMG_LEFT                32804
#define ID_CTRL_IMG_TOP                 32805
#define ID_CTRL_IMG_BOTTOM              32806
#define ID_COLLAPSE_ALL_ENTIRE_TREE     32806
#define ID_CTRL_IMG_SCALE               32807
#define ID_CTRL_IMG_STRETCH             32808
#define IDC_COUNT_SUBTREE               32808
#define ID_CTRL_IMG2_OPEN               32809
#define IDC_COUNT_ENTIRE_TREE           32809
#define ID_CTRL_IMG_STRETCHSM           32810
#define ID_CTRL_IMG_TILE                32811
#define ID_CTRL_IMG2_ROTATELEFT         32812
#define ID_CTRL_IMG2_ROTATERIGHT        32813
#define ID_CTRL_IMG_STRETCHXY           32814
#define ID_CTRL_IMG_CENTERX             32815
#define ID_CTRL_IMG_CENTERY             32816
#define ID_CTRL_IMG2_ZOOMIN             32817
#define ID_CTRL_IMG2_ZOOMOUT            32818
#define ID_CTRL_IMG2_STRETCHNOTHING     32819
#define ID_CTRL_IMG2_STRETCHHEIGHT      32820
#define ID_CTRL_IMG2_STRETCHWIDTH       32821
#define ID_CTRL_IMG2_STRETCHALL         32822
#define ID_CTRL_JUKEBOX_PLAY            32823
#define ID_CTRL_JUKEBOX_STOP            32824
#define ID_CTRL_JUKEBOX_PAUSE           32825
#define ID_CTRL_JUKEBOX_FRAMESTEP       32826
#define ID_CTRL_JUKEBOX_GRAPHEDIT       32827
#define ID_CTRL_JUKEBOX_MUTE            32828
#define ID_CTRL_JUKEBOX_LOOP            32829
#define ID_CTRL_JUKEBOX_FULLSCREEN      32830
#define ID_CTRL_JUKEBOX_FILE            32831
#define ID_CTRL_JUKEBOX_PROPERTIES      32832
#define ID_CTRL_MEDIAPLAYER_PLAY        32833
#define ID_CTRL_MEDIAPLAYER_STOP        32834
#define ID_CTRL_MEDIAPLAYER_PAUSE       32835
#define ID_CTRL_MEDIAPLAYER_MUTE        32836
#define ID_CTRL_MEDIAPLAYER_LOOP        32837
#define ID_CTRL_MEDIAPLAYER_FULLSCREEN  32838
#define ID_CTRL_LISTMULTIOPTION_EDITABLE 32839
#define ID_CTRL_LISTMULTIOPTION_GRIDLINES 32840
#define ID_CTRL_LISTMULTIOPTION_AUTOEDIT 32841
#define ID_CTRL_LISTMULTIOPTION_SHOWSELECTION 32842
#define ID_CTRL_LISTMULTIOPTION_HORIZONTALGRID 32843
#define ID_CTRL_LISTMULTIOPTION_VERTICALGRID 32844
#define ID_CTRL_LISTMULTIOPTION_COLRESIZE 32845
#define ID_CTRL_LISTMULTIOPTION_LEFT    32846
#define ID_CTRL_LISTMULTIOPTION_CENTER  32847
#define ID_CTRL_LISTMULTIOPTION_RIGHT   32848
#define ID_CTRL_LISTMULTIOPTION_FONTBKCOLOR 32849
#define ID_CTRL_LISTMULTIOPTION_BKCOLOR 32850
#define ID_CTRL_LISTMULTIOPTION_GRIDLINESCOLOR 32851
#define ID_CTRL_LISTMULTIOPTION_NORMALGRIDLINES 32852
#define ID_CTRL_LISTMULTIOPTION_NORMALCHKBOX 32853
#define ID_VIEW_CTRL_GRAPHBARCTRL       32854
#define ID_VIEW_CTRL_INFOBAR            32855
#define ID_VIEW_CTRL_EDITINFOBAR        32855
#define ID_CTRL_INFOBAR_FONTSTYLE       32856
#define ID_CTRL_EDITINFOBAR_FONTSTYLE   32856
#define ID_CTRL_INFOBAR_FONTCOLOR       32857
#define ID_CTRL_EDITINFOBAR_FONTCOLOR   32857
#define ID_CTRL_INFOBAR_BKCOLOR         32858
#define ID_CTRL_EDITINFOBAR_BKCOLOR     32858
#define ID_VIEW_CTRL_INFOCTRL           32859
#define ID_VIEW_WORKSPACETABVIEW        32861
#define ID_VIEW_TOOLBAR_IMAGECTRL       32863
#define ID_VIEW_CTRL_OLEDBDLG           32864
#define ID_CTRL_OLEDBDLG_RUNQUERY       32866
#define ID_CTRL_OLEDBDLG_MSACESS        32868
#define ID_CTRL_OLEDBDLG_MSSQLSERVER    32869
#define ID_CTRL_OLEDBDLG_MSORACLE       32870
#define ID_CTRL_OLEDBDLG_ORACLE         32871
#define ID_CTRL_OLEDBDLG_MYSQL          32872
#define ID_CTRL_OLEDBDLG_DB2            32873
#define ID_VIEW_CTRL_DXFCADDLG          32874
#define ID_CTRL_DXFCADDLG_OPEN          32876
#define ID_EDIT_ADD_CHILD               32878
#define ID_EDIT_ADD_SIBLING             32879
#define ID_CTRL_IMG3_OPEN               32880
#define ID_EDIT_COLLAPSE_ALL_ENTIRE_TREE 32880
#define ID_CTRL_IMG3_RESET              32881
#define IDC_EDIT_EXPAND_ALL_TREE        32881
#define ID_CTRL_IMG3_BLUR               32882
#define ID_EDIT_RENAME                  32882
#define ID_CTRL_IMG3_GRAY               32883
#define ID_CTRL_IMG3_SHARP              32884
#define ID_EDIT_DELETE_ITEM             32884
#define ID_CTRL_IMG3_INVERT             32885
#define ID_EDIT_DELETE_ALL_ITEMS        32885
#define ID_EDIT_SORT_SUBTREE_ALPHABETIC 32886
#define ID_EDIT_SORT_SUBTREE_NUMERIC    32887
#define IDC_EDIT_COUNT_SUBTREE          32889
#define IDC_EDIT_COUNT_ENTIRE_TREE      32890
#define ID_EDIT_CALCULATE_LEVEL         32891
#define ID_SETTINGS_FONTSIZE            32892
#define ID_SETTINGS_FONTFACE            32892
#define ID_SETTINGS_TREE_FORMAT_PROP    32893
#define ID_SETTINGS_NODECLR             32894
#define ID_CTRL_METER_COLOR             32895
#define ID_SETTINGS_LINKTEXTCLR         32895
#define ID_CTRL_METER_MAX               32896
#define ID_SETTINGS_NODETEXTCLR         32896
#define ID_CTRL_METER_MIN               32897
#define ID_SETTINGS_LEAFTEXTCLR         32897
#define ID_CTRL_METER_UNITS             32898
#define ID_SETTINGS_LINKCLR             32898
#define ID_CTRL_METER_RANGEDECIMALS     32899
#define ID_SETTINGS_LEAFCLR             32899
#define ID_VIEW_INDUCTION_FRAME_DLG     32900
#define ID_CTRL_METER_VALUEDECIMALS     32901
#define ID_INDUCTION_BUILDTREE          32901
#define ID_BUTTONLISTBOX1               32902
#define ID_BUTTONLISTBOX2               32903
#define ID_BUTTONLISTBOX3               32904
#define ID_CTRL_NSCHART_PIE             32905
#define ID_INDUCTION_OPENDB             32905
#define ID_CTRL_NSCHART_BAR             32906
#define ID_CTRL_NSCHART_GRAY            32907
#define ID_CTRL_NSCHART_COLOR           32908
#define ID_CTRL_NSCHART_LINE            32909
#define ID_CTRL_NSCHART_ADD             32910
#define ID_BUILD                        32910
#define ID_CTRL_NSCHART_DEL             32911
#define ID_CTRL_NSCHART_MODIFY          32912
#define ID_VIEW_AIPI_FRAME_DLG          32913
#define ID_EDIT_FIND_EXT                32914
#define ID_BUTTON32915                  32915
#define ID_EDIT_FINDINFILES_STOP        32919
#define ID_PROJ_OPEN                    32920
#define ID_PROJ_SAVE                    32921
#define ID_PROJ_SAVE_AS                 32922
#define ID_TEST                         32924
#define ID_PROJ_NEW                     32925
#define ID_PROJ_CLOSE                   32926
#define ID_CTRL_CHARTBAR_ADD            32927
#define ID_CTRL_CHARTBAR_DEL            32928
#define ID_CTRL_CHARTBAR_BCKCOLOR       32929
#define ID_CTRL_CHARTBAR_LEGENDVISIBLE  32930
#define ID_CTRL_CHARTBAR_PANENABLE      32931
#define ID_CTRL_CHARTBAR_ZOOMENABLE     32932
#define ID_CTRL_CHARTBAR_TITLE          32933
#define ID_CTRL_CHARTBAR_AXIS           32934
#define ID_FILE_SAVE_ALL                32935
#define ID_VIEW_PROPERTIESBAR           32937
#define ID_CTRL_CALENDAR_GOTODATE       32938
#define ID_BUTTON32941                  32941
#define ID_BUTTON32942                  32942
#define ID_BUTTON32943                  32943
#define ID_OPTIONS_VIEW_WHITESPACE      32946
#define ID_OPTIONS_VIEW_LINEEND         32947
#define ID_OPTIONS_INDENTLINE           32948
#define ID_OPTIONS_VIEW_INDENTLINE      32949
#define ID_VIEW_ZOOM                    32950
#define ID_OPTIONS_AUTOINDENT           32951
#define ID_OPTIONS_DELETEALLMARKERS     32952
#define ID_OPTIONS_COMMENTBLOCK         32953
#define ID_OPTIONS_COMMENTLINE          32954
#define ID_OPTIONS_UNCOMMENT            32955
#define ID_EDIT_GOTO                    32958
#define ID_OPTIONS_AUTOCOMPLETE         32959
#define ID_OPTIONS_UPPERCASE            32960
#define ID_OPTION_LOWERCASE             32961
#define ID_BUILD_CURRENT_FILE           32962
#define ID_BUILD_PROJECT                32963
#define ID_BUILD_EXECUTE                32964
#define ID_BUILD_INSERT_BREAKPOINT      32965
#define ID_BUILD_CLEAR_BREAKPOINTS      32966
#define ID_BUILD_STEP_FORWARD           32967
#define ID_BUILD_STEP_BACKWARD          32968
#define ID_BUILD_BREAKPOINT_WINDOW      32969
#define ID_BUILD_START_DEBUG            32970
#define ID_OPTIONS_MODIFIED_NOTFICATION 32971
#define ID_EXEC_LOAD                    32972
#define ID_EXEC_RUN                     32973
#define ID_CTRL_MULTIOPTION_NONE        33041
#define ID_FILE_FILES_MRU1              34044
#define ID_FILE_PROJ_MRU1               34060
#define ID_CTRL_CALENDAR_TODAY          42956
#define ID_CTRL_CALENDAR_SUNDAY         42957
#define ID_CTRL_CALENDAR_MONDAY         42958
#define ID_CTRL_CALENDAR_TUESDAY        42959
#define ID_CTRL_CALENDAR_WEDNESDAY      42960
#define ID_CTRL_CALENDAR_THURSDAY       42961
#define ID_CTRL_CALENDAR_FRIDAY         42962
#define ID_CTRL_CALENDAR_SATURDAY       42963
#define ID_CTRL_CALENDAR_MARK           42964
#define ID_CTRL_CALENDAR_ADD            42965
#define ID_CTRL_CALENDAR_CLEAR          42966
#define ID_CTRL_GRAPHBAR_TOOLTIP        42978
#define ID_CTRL_GRAPHBAR_SQUAREPOINTS   42979
#define ID_CTRL_GRAPHBAR_AXIS           42980
#define ID_CTRL_GRAPHBAR_AXISPROP       42982
#define ID_CTRL_GRAPHBAR_SCATTER        42983
#define ID_CTRL_GRAPHBAR_COORDINATES    42984
#define ID_CTRL_GRAPHBAR_ANIMATION      42986
#define ID_CTRL_GRAPHBAR_QUIT           42987
#define ID_CTRL_CRONOMETER_BACKGROUND   42998
#define ID_CTRL_CRONOMETER_FOREGROUND   42999
#define ID_CTRL_CRONOMETER_CLOCK        43000
#define ID_CTRL_CRONOMETER_COUNT        43001
#define ID_CTRL_CRONOMETER_STOP         43002
#define ID_CTRL_CRONOMETER_INTERVALS    43003
#define ID_CTRL_CRONOMETER_START        43004
#define ID_CTRL_CRONOMETER_RESET        43005
#define ID_CTRL_LISTBAR_BACKCOLOR       43010
#define ID_CTRL_LISTBAR_FONT            43011
#define ID_CTRL_LISTBAR_TEXTBKCOLOR     43012
#define ID_CTRL_LISTBAR_ADD             43015
#define ID_CTRL_LISTBAR_DELETE          43016
#define ID_CTRL_MULTIOPTION_EDIT        43019
#define ID_CTRL_MULTIOPTION_SORT        43020
#define ID_CTRL_MULTIOPTION_CHECKALL    43021
#define ID_CTRL_MULTIOPTION_CHECKINVERT 43022
#define ID_CTRL_MULTIOPTION_UNCHECKALL  43023
#define ID_CTRL_MULTIOPTION_NORMAL      43026
#define ID_CTRL_MULTIOPTION_SINGLE      43027
#define ID_CTRL_MULTIOPTION_DISABLED    43028
#define ID_CTRL_MULTIOPTION_DELETE      43029
#define ID_CTRL_MULTIOPTION_GRIDLINES   43030
#define ID_CTRL_MULTIOPTION_MOVEUP      43031
#define ID_CTRL_MULTIOPTION_MOVEDOWN    43032
#define ID_CTRL_MULTIOPTION_MOVETOP     43033
#define ID_CTRL_MULTIOPTION_MOVEBOTTOM  43034
#define ID_CTRL_MULTIOPTION_SELECTALL   43035
#define ID_CTRL_MULTIOPTION_SELECTINVERT 43036
#define ID_EDIT_FINDINFILES             57645
#define ID_WORKSPACETABVIEW             0xe882
#define ID_OUTPUTTABVIEW                0xe883
#define ID_INDICATOR_LINE               61446
#define IDS_LINE_INDICATOR              61447
#define ID_INDICATOR_STYLE              61448
#define IDS_STYLE_INDICATOR             61449
#define ID_INDICATOR_FOLD               61450
#define IDS_FOLD_INDICATOR              61451
#define ID_INDICATOR_PROG               61452
#define IDS_PROG_INDICATOR              61453
#define IDS_RESTART                     61454
#define IDS_DOC_INDICATOR               61455
#define ID_INDICATOR_DOC                61456
#define IDC_FINDFILESCOMBO              61457
#define IDS_NEWPROJECTWIZARD            61460
#define IDS_HEADERTITLE_PROJ_PAGE1      61461
#define IDS_HEADERSUBTITLE_PROJ_PAGE1   61462
#define IDS_HEADERTITLE_PROJ_PAGE2      61463
#define IDS_HEADERSUBTITLE_PROJ_PAGE2   61464

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        380
#define _APS_NEXT_COMMAND_VALUE         32974
#define _APS_NEXT_CONTROL_VALUE         1236
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
