del *.obj /s /q
del *.sbr /s /q
del *.bsc /s /q
del *.aps /s /q
del *.ncb /s /q
del *.opt /s /q
del *.plg /s /q
del *.idb /s /q
del *.pch /s /q
del *.pdb /s /q
del *.ilk /s /q
del *.lib /s /q
del *.exp /s /q
del *.res /s /q
